### ISSUE TITLE
Software Catalog Deep Dive - syntax error in confg map 

### ISSUE THREAD

**Issue by bugbiteme** [RedHatQuickCourses/devhub-build#22]
Software Templates->Software Catalog Deep Dive
Step 2 code snippet
```
    catalog:
      providers:
        github:
          providerId:
            organization: "${GITHUB_ORGANIZATION}"
            catalogPath: '/rhdh-discovery/catalog-info.yaml'
            filters:
              branch: 'main'
              repository: '.'*
```
I am getting a syntax error with `repository: '.'*`

should possibly be `repository: '.*'`
